export const SHIP = {
  THRUST_FORCE: 132,
  YAW_RATE: 1.4,
  MAX_PITCH: Math.PI * 0.28,
  PITCH_SMOOTH: 2,
  BANK_ANGLE_MAX: 0.52,
  BANK_SMOOTH: 7,
  VELOCITY_DAMPING: 0.992,
  BOOST_MULTIPLIER: 5.0,

  EXHAUST_MIN: 25,
  EXHAUST_MAX: 75,
  MAX_SPEED_FOR_EXHAUST: 800,

  SPAWN_RADIUS: 7500,
  SPAWN_Y: 0,
} as const;

export const MAP = {
  BOUNDARY_RADIUS: 9000,
  Y_MIN: -950,
  Y_MAX: 950,
  BOUNDARY_WARNING: 75,
  BOUNDARY_FORCE: 150,
} as const;

export const NETCODE = {
  TICK_HZ: 30,
  TICK_DT: 1 / 30,
  INTERPOLATION_DELAY_MS: 100,
} as const;

export const UI = {
  STARTING_LEVEL: 4,
  STARTING_XP: 320,
  XP_PER_LEVEL: 1000,
  STARTING_COINS: 1250,
} as const;

export const DEBUG = {
  PLAYER_GLOW: false,
} as const;